config/routes.rb
Rails.application.routes.draw do
  post '/products/confirmation'
  get "/products/pay"
  post 'products/success'
  get 'products/success'
  post 'products/failure'
  get 'products/failure'
  resources :products

  resources :products
  devise_for :users
  get 'comments/create'

  resources :posts do
    resources :comments, only: [:create]
  end

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :product
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/success.rb
class Success < ActiveRecord::Base
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence:true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comments_params)
    if @comment.save
      redirect_to @post, notice: "El comentario fue creado con exito"
    else
      redirect_to @post, alert: "El comentario no fue creado"
    end
  end

  private
  def comments_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json

  def show
    @comment = @post.comments.build
    @last_comments = @post.comments.last(5)#se agrega para podeer llamar a los comentarios desde las vistas
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: [:confirmation, :failure, :success]
  before_action :set_product, only: [:show, :edit, :update, :destroy]


  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  def pay
    @product = Product.find(params[:id])
    @payment = Payment.create

    @payment.oreder_id = @payment.id.to_s + SecureRandom.random_number(10).to_s
    @payment.session_id = SecureRandom.random_number(10)
    @payment.amount = @product.precio
    @payment.status = false
    @payment.product = @product
    @payment.save

    @tbk_url_cgi = "http://186.64.122.15/cgi-bin/valeskyta/tbk_bp_pago.cgi"
    @tbk_tipo_transaccion = "TR_NORMAL"
    @tbk_url_exito = "http://valeska.beerly.cl/products/success"
    @tbk_url_fracaso = "http://valeska.beerly.cl/products/failure"


  end

  def confirmation
    payment = Payment.where(oreder_id: params[:TBK_ORDEN_COMPRA]).where(session_id: params[:TBK_ID_SESION]).first
    rejected = false
    rejected = true if payment.nil?
    rejected = true if payment.amount.to_s + "00" != params[:TBK_MONTO]
    rejected = true if !params.has_key?(:TBK_RESPUESTA) || !params.has_key?(:TBK_ORDEN_COMPRA) || !params.has_key?(:TBK_TIPO_TRANSACCION) || !params.has_key?(:TBK_MONTO) || !params.has_key?(:TBK_CODIGO_AUTORIZACION) || !params.has_key?(:TBK_FECHA_CONTABLE) || !params.has_key?(:TBK_HORA_TRANSACCION) || !params.has_key?(:TBK_ID_SESION) || !params.has_key?(:TBK_ID_TRANSACCION) || !params.has_key?(:TBK_TIPO_PAGO) || !params.has_key?(:TBK_NUMERO_CUOTAS) || !params.has_key?(:TBK_VCI) || !params.has_key?(:TBK_MAC)
    rejected = true if payment.status

    payment.status = true
    payment.payment_type = params[:TBK_TIPO_PAGO]
    if rejected
      render text: "RECHAZADO"
    else
      if params[:TBK_RESPUESTA] == "0"
        #Aca hay lucas :)
        payment.card_last_numbers = params[:TBK_FINAL_NUMERO_TARJETA]
        payment.authorization = params[:TBK_CODIGO_AUTORIZACION]
      end
      render text: "ACEPTADO"
    end
    payment.save
  end

  def success
    @payment = Payment.where(oreder_id: params[:TBK_ORDEN_COMPRA]).where(session_id: params[:TBK_ID_SESION]).first

  end

  def failure

  end


  # def confirmation
  #   logger.info "hola me estoy llamando"
  #   render text: "ACEPTADO"
  # end
  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:description, :precio, :cantidad)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/comments/_comment.html.erb
  <div class="comment" style="background-color:beige">
    <%= comment.comment %>
  </div>

app/views/comments/_form.html.erb
<div calss="new-comment" style="background-color:pink">
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :comment %>
  <%= f.text_area :comment %>

  <%= f.submit "enviar" %>
  <% end %>
</div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/layouts/_navbar.html.erb
<% if user_signed_in?%>
	<span> Hola <%= current_user.name %> </span>
  	<%= link_to "salir", destroy_user_session_path, method: "Delete" %>
<% else %>

	<%= link_to "ingresar", new_user_session_path %>
	<%= link_to "registrarse", new_user_registration_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>July3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

       <div class="notice"><%= notice %></div>
       <div class="alert"><%= alert %></div>

<%= render "layouts/navbar" %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Comentarios</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.comments.count %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="post">
 <p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
</div>

<%= render partial: "comments/comment", collection: @last_comments %>
<%= render "comments/form" %>

</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.number_field :precio %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/failure.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
	<link rel="stylesheet" href="">
</head>
<body>
	<h1>Transacción Rechazada Nº</h1>
	<p>Las posibles causas de este rechazo son:</p>
	<p>Error en el ingreso de los datos de su tarjeta de crédito (fecha y/o código de seguridad)</p>
	<p>Su tarjeta de crédito no cuenta con el cupo necesario para cancelar la compra</p>
	<p>Tarjeta aún no havilitada en el sistema financiero.</p>


</body>
</html>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Precio</th>
      <th>Cantidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.description %></td>
        <td><%= product.precio %></td>
        <td><%= product.cantidad %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'pagar', "products/pay?id=#{product.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/pay.html.haml
!!!
%html
  %head
    %title
  %body
:javascript

  var form = document.createElement("form");
  form.method = "POST";
  form.action = '#{@tbk_url_cgi}';

  var element1 = document.createElement("input");
  element1.value = '#{@tbk_tipo_transaccion}';
  element1.name = "TBK_TIPO_TRANSACCION";
  element1.type = "hidden";
  form.appendChild(element1);

  var element2 = document.createElement("input");
  element2.value = '#{@payment.amount.to_s + "00"}';
  element2.name = "TBK_MONTO";
  element2.type = "hidden";
  form.appendChild(element2);

  var element3 = document.createElement("input");
  element3.value = '#{@payment.oreder_id}';
  element3.name = "TBK_ORDEN_COMPRA";
  element3.type = "hidden";
  form.appendChild(element3);

  var element4 = document.createElement("input");
  element4.value = '#{@payment.session_id}';
  element4.name = "TBK_ID_SESION";
  element4.type = "hidden";
  form.appendChild(element4);

  var element5 = document.createElement("input");
  element5.value = '#{@tbk_url_exito}';
  element5.name = "TBK_URL_EXITO";
  element5.type = "hidden";
  form.appendChild(element5);

  var element6 = document.createElement("input");
  element6.value = '#{@tbk_url_fracaso}';
  element6.name = "TBK_URL_FRACASO";
  element6.type = "hidden";
  form.appendChild(element6);

  document.body.appendChild(form);
  form.submit();

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @product.precio %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @product.cantidad %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/success.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
	<link rel="stylesheet" href="">
</head>
<body>
	<h1>Datos de tu pago</h1>
	<p><span>Nombre compra</span><%= [@product, @payment] %></p>
	<p><span>URL Comercio</span></p>
	<p><span>ID Transacción</span></p>
	<p><span>Número de orden</span></p>
	<p><span>Tipo de transacción</span></p>
	<p><span>Tipo de Pago</span></p>
	<p><span>Código Autorización</span></p>
	<p><span>Número de cuotas</span></p>
	<p><span>Tipo Cuotas</span></p>
	<p><span>Monto Transacción</span></p>
	<p><span>Fecha Transacción</span></p>
	<p><span>Nombre Comercio</span></p>
	<p><span>Tarjeta terminada en</span> <%= @payment.to_json%></p>

</body>
</html>